### PR TITLE
Recipes of new Japanese singing voice databases

### PR DESCRIPTION
**Pull request by taroushirani**
Hello, I made some recipes of Japanese singing voice databases.

1.  Ofuton P Utagoe DB (singing voice database) (male) [1]
2.  Yuuri Natsume's singing voice database (male) [2]
3. Oniku Kurumi Utagoe DB (female) [3]

There are some known issues:
(1)  These databases have some mismatches between HTS mono-phone label files and musicxml files(especially Yuuri Natsume's singing voice database), so I borrowed the python codes  from kiritan_singing[4] to keep their consistency.
(2) The term of service of these singing voice databases are written in Japanese only, so it may be difficult for non-Japanese speaker to agree their license.
(3) Some of these databases contain the label of unvoiced vowels and make use of the modified version of sinsy dictionary.  The copyright notice of the dictionary is under egs/{ofuton_p_utagoe_db, natsume_singing, oniku_kurumi_utagoe_db}/dic/COPYING.

 1. https://sites.google.com/view/oftn-utagoedb/%E3%83%9B%E3%83%BC%E3%83%A0
 2. https://amanokei.hatenablog.com/entry/2020/04/30/230003
 3. http://onikuru.info/db-download/ 
 4. https://github.com/r9y9/kiritan_singing

### CODE REVIEW

**Review by r9y9 — CHANGES_REQUESTED** [review]
Thank you for this PR! All looks very nice to me. For the recipe structure, could you please reduce duplicated code and remove unnecessary files? More specifically,

- sinsy's dictionary files are hard copied across multiple recipes. We'd want to keep only one instance, and symlink them if necessary.
- shift-jis euc-jp dictionaries are not used, right? I have only used the utf-8 one.
- If you want to include dictionary files, how about putting them into egs/_common directory?
- python files (gen_lab.py, finalize_lab.py, etc) are hard copied across different recipes. Would be very nice if we can make common ones to avoid dup.

**Comment by taroushirani** [comment]
As far as I know, sinsy requires all japanese dictionaries even if we don't use them[1], because src/lib/converter/ConfManager.cpp reads them in parallel[2].  If we want to delete the unnecessary dictionaries, we have to hack sinsy first of all(it may be quite easy).

1. https://gist.github.com/taroushirani/02e9eeba57cbd6265e7d00e2ccbcc405
2. https://github.com/r9y9/sinsy/blob/31e372e61ac83a15cb48a6d2bdbcb5e64df60b97/src/lib/converter/ConfManager.cpp#L134

It will be easy for us to unify the modified sinsy dictionaries for unvoiced vowels, but the python codes are customized for each singing voice databases to absorb the differences such as directory structure, time unit, handling of "cl" phoneme and so on.  I'll need some more time to unify them.

**Comment by r9y9** [comment]
Ah I see..... For the dictionary issues, it could be fixed on the sinsy side. It's okay to keep as is.

> It will be easy for us to unify the modified sinsy dictionaries for unvoiced vowels, but the python codes are customized for each singing voice databases to absorb the differences such as directory structure, time unit, handling of "cl" phoneme and so on. I'll need some more time to unify them.

It's okay If there's a reason to do this. We can revisit it in the future if we might want to improve. Thanks for your explanation.

Let me know once you think it is good to go. I will merge this PR.

**Comment by r9y9** [comment]
BTW, I like the idea using the yaml config for run.sh. (looks like you are using https://stackoverflow.com/questions/5014632/how-can-i-parse-a-yaml-file-from-a-linux-shell-script?). How about putting it into https://github.com/r9y9/nnsvs/tree/master/utils?

**Comment by taroushirani** [comment]
Thank you for your comments.  I used "--alow-unrelated-histories" option to preserve log when importing the recipes from my own repositories, but I noticed that this may destroy the repository when someone use git rebase.  I'll submit PR from the another branch which is newly created.

**Pull request closed without merging**
