### PR TITLE
Neural Source Filter waveform models (NSF) support

### PR DESCRIPTION
**Pull request by taroushirani**
Hello. I made sample implementation of [Neural Source Filter waveform models(NSF)](https://nii-yamagishilab.github.io/samples-nsf/) support.

1. If nsf_root_dir is unspecified or not found, run.sh download NSF into downloads directory automatically.
2. All NSF related data and outputs are stored in exp/yoko/nsf.
3. I could not find the rules about assigning stage no, so I assign stage 7-10 to each NSF related process(downloading, data preparation, training, evaluation).
4. Training data are the combination of mgc,f0,bap and extracted from dump/org/\*/out_acoustic/\*.npy.  The process of training NSF  seems to work well as far as I listen to the output of NSF evaluation(it is stored in exp/yoko/nsf/test_output_dirs and the data to synthesize this are directly extracted from original wav file).  But when using acoustic features generated by NNSVS, sound quality of generated wavs are unsatisfactory.
5. For convenience I prepare the pretrained NSF model(https://drive.google.com/file/d/1EIaeiQukNt7lsXSqFVWzryujFhUdqkgi/view?usp=sharing).

Please advise me to improve quality of sounds.

### CODE REVIEW

**Comment by r9y9** [comment]
Great! Support for NSF models is defenitely nice. I will have a closer look at the code and let you know if I have any comments.

**Comment by r9y9** [comment]
One quick comment: Have you tried adapting a model trained on a speech corpus? I am guessing that the amount of data of NIT-song070 is not sufficient enough to train NSF models from scratch. We may want to utizlie the existing speech corpra to obtain good initial weights of NSF models.

**Comment by taroushirani** [comment]
Thank you for your rapid comment. Does "adapting" mean fine-tuning from the model pretrained with a speech corpus?  I haven't tried it yet. I couldn't think of using the pretrained model with speeches instead of singing voices.

Fortunately I have [the model trained with CMU Arctic speech corpus](https://drive.google.com/file/d/1YhUrUyoJXOi8p3eXIdTIetzbQYR7NhdP/view?usp=sharing)(generated by 00_demo.sh contained in NSF project), so I'll try it and report the result.

**Comment by r9y9** [comment]
Yes, I mean fine-turning parameters from a pretrained model. It makes sense since speech and singing voice share very similar structure. Please make sure that same acoustic features are used.

**Comment by taroushirani** [comment]
Thank you for pointing it out. I forgot that the original demo of NSF made use of different acoustic features.  I extracted acoustic features from CMU Arctic speech corpus as I did in my Pull Request, and now I'm trying to train NSF model with them.

Apart from that, I found that I used numpy.save instead of numpy.ndarray.tofile by mistake.  I did not notice that NSF could not handle npy format(it can handle wav file or little-endian, 32bit-float binary only).  This may be the reason why I couldn't get good results from the previous experiments.

**Comment by taroushirani** [comment]
I created two pretrained NSF models, [1]one is trained with CMU Arctic corpus and [2]the other is the adapted version of the former to NIT-SONG070 data-set.  With correcting wrong file formats, the quality of generated WAVs with shorter length(<30 sec) seems to be improved, but the quality of generated WAVs with longer length(>30 sec) [3] gets worse over time.

This is independent from whether the NSF model is trained from scratch or adapted from a larger speech corpus, so I think this is independent from the amount of training data.  And there is nothing wrong with the WAVs synthesized by PyWorld with the same acoustic features, so there is nothing wrong with generation process of acoustic features.

I have no idea about the cause of this phenomenon currently and it may take more time to find it.

1. https://drive.google.com/file/d/1_U9WfatzEHDmUef0Wnu0qZsrfYjJas2w/view?usp=sharing
2. https://drive.google.com/file/d/1EIaeiQukNt7lsXSqFVWzryujFhUdqkgi/view?usp=sharing
3. https://soundcloud.com/user-883019797/nnsvs_nit_song070_01_svs_nsf_mimirobo_from_scratch_1

**Comment by r9y9** [comment]
Hi, thank you for your great effort! Good to know that you got reasonable results after fixing wrong file format. For the bad quality issues on long utterances, it sounds like a bug to me. NSFs are non-autoregressive models, thus the generation process should be same regardless of the length of acoustic features. I guess there might be a  bug in the upsampling module of NSFs, which uses LSTMs.

**Comment by taroushirani** [comment]
Hello, thank you for your comment. I have confirmed this phenomenon occurs with default NSF settings (with default acoustic features of mel-spectrum and f0 and with default test data of CMU Arctic corpus).  I'll report this to the upstream author.

**Comment by taroushirani** [comment]
nii-yamagishilab/project-NN-Pytorch-scripts#2

**Comment by TonyWangX** [comment]
Just to paste the reply here https://github.com/nii-yamagishilab/project-NN-Pytorch-scripts/issues/2#issuecomment-667664621:


I looked into the code, and I think I find the issue(s).

### 1. Numerical problem with `torch.cumsum()` in sine generator
This is the main issue.

#### Why
When generating sine, the phase is accumulated by torch.cumsum(f0/sampling_rate * 2 * np.pi). When the utterance is too long, for example 1 minute in length, torch.cumsum() becomes inaccurate. The generated sine will be weird. 

#### How to 
The solution is to do phase wrapping over f0/sampling_rate. Because sin((f0/sampling_rate - K) * 2 *np.pi) = sin((f0/sampling_rate) * 2 *np.pi - 2 K pi) sin((f0/sampling_rate) * 2 *np.pi, we can wrap the value of f0/sampling_rate to make it between (0, 1).

In my CUDA implementation of NSF, the cumsum is a for loop, and I embedded a similar wrapping function "https://github.com/nii-yamagishilab/project-CURRENNT-public/blob/69ce115688b2686810a43cbb27d1daf699e2de15/CURRENNT_codes/currennt_lib/src/layers/SignalGenLayer.cu#L252"

In the Pytorch implementation, there is no for loop. Therefore, the implementation is to add -1.0 to f0/sampling_rate at time steps where the accumulated phase will cross 1.0. 

It is hard to explain in words. The code is here
https://github.com/nii-yamagishilab/project-NN-Pytorch-scripts/blob/09ef1ba2b622b8f0bbec9659594e4ead243844b5/project/hn-sinc-nsf-9/model.py#L476-L487

The same modification to hn-nsf/model.py in the branch https://github.com/nii-yamagishilab/project-NN-Pytorch-scripts/tree/newfunctions.

cyc-noise-NSF doesn't need to update because it has used a similar method when aligning the generated pulse-train.
https://github.com/nii-yamagishilab/project-NN-Pytorch-scripts/blob/09ef1ba2b622b8f0bbec9659594e4ead243844b5/project/hn-sinc-nsf-9/model.py#L500-L512

#### Note
There is no need to re-train the model if the training data sequences are truncated into short segments during training (less than 10s? see truncate_seq in config.py). Please just:

1. update model.py 
2. do generation

I attached two samples from pre-trained hn-sinc-nsf-9. The file long-4-bad.wav is the one before revising model.py; long-4.wav is the one after modification.
https://www.dropbox.com/sh/gf3zp00qvdp3row/AACrDZEiUlFQzmBF0fFCEfGRa/temp/issue-long-wav-202008?dl=0&subfolder_nav_tracking=1


### 2. BLSTM in conditioin module
#### Why
BLSTM is not time-length agnostic. Training data are short trimmed segments, while generation data can be very long utterances

#### How to
Replace BLSTM in condition module with CNN layers. I added hn-sinc-nsf-10 as one example.
https://github.com/nii-yamagishilab/project-NN-Pytorch-scripts/blob/newfunctions/project/hn-sinc-nsf-10/model.py

#### Note
This is not really important for cmu-arctic. When concatenating multiple utterances, the silence between utterances will tell the BLSTM to reset. You can fix issue 1 and use the trained NSF to generate long utterances.

### 3. Concatenation of acoustic features
This is the least important one. When during experiment on long utterances, we concatenate the Mel-spectrogram or F0 of multiple utterances as a single file. 

#### why
However, Mel-spectrogram and F0 of the same utterance may have different length due to the extraction tools. If we directly concatente features, the length mismatch will make Mel-spectrogram and F0 out of alignment. 
Mel_1 [0, 100]
F0_1 [0, 99]
Mel_2 [0, 110]
F0_2 [0, 108]
Mel_1+Mel_2 [0, 210]
F0_1+F0_2 [0, 207]

#### how to
Do manual trimming before concatenation
Mel_1 <- Mel_1 [0, 0:99]
Mel_2 <- Mel_2 [0, 0:108]
Mel_1+Mel_2 [0, 207]
F0_1+F0_2 [0, 207]

#### note
This is not a problem for a single utterance because the default data IO will trim the longer feature sequence, for example.
Mel_1 <- Mel_1 [0, 0:99]


### 4. summary
The first issue is the most important. Please try the updated model.py

For default 00_demo.sh on CMU-arctic, it is OK to use the pre-trained model to generate very long utterances. For models trained on other corpus, the BLSTM may become an issue. 

Depending the way to prepare the input features for long utterances, the third issue with feature concatenation may also matter.

**Comment by taroushirani** [comment]
Hello. As written in the  issues#2 of NSF, the poor quality issue of long utterance is solved by modifying model.py of hn-sinc-nsf.   The improved version of the previous bad example is here:  https://soundcloud.com/user-883019797/mimirobo

**Comment by r9y9** [comment]
I am so sorry for being unresponsive for a long time. I was busy for preparing ICASSP 2021 and lots of my primary work-related things T.T And thanks again for the huge effort trying the neural vocoder in an SVS framework.

As you know, the bottleneck of the current nnsvs is the acoustic model (i.e., the module predicting acoustic features from musical/linguistic contexts). Let me first trying to improve the acoustic model first, and then let me work together on the neural vocoder part. When the acoustic model is in good shape, I will take a more closer look at your implementation and give you more detailed feedback if I have any. Please be patient for a while!

**Comment by taroushirani** [comment]
I'm sorry for overlooking your comment.   I achieved accumulating know-how about training and operation of NSF, and I'm in no hurry for code review.   I'm looking forward to the improved acoustic model(I also try to improve it by myself).

**Comment by r9y9** [comment]
I've revisited the NSF support today. I started initial experiments and it seems to be working reasonably well. I'll share you code and experimental results later, but I wanted to first let you know that I managed to make NSF work with nnsvs thanks to your PR (in fact, the code has been changed dramatically, but I found your code very helpful anyways).

**Comment by r9y9** [comment]
Hers are samples:

- WORLD: https://soundcloud.com/r9y9/20220321-kiritan-test-svs-roshin-yuukai-vuv-fixed2?in=r9y9/sets/dnn-based-singing-voice&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing
- NSF: https://soundcloud.com/r9y9/20220404-kiritan-test-svs-roshin-yuukai-with-nsf?utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing

NOTE: Training for NSF is still 5k steps out of 40 k steps

**Comment by r9y9** [comment]
Still in a very very early stage though, a recipe for training NSF is up now: https://github.com/r9y9/nnsvs/tree/optuna-test1/recipes/mixed/voc-multidb-latest

```
pip install git+https://github.com/r9y9/ParallelWaveGAN@nnsvs
```

is necessary to train NSF models.

I will add a few more recipes with documentation later (maybe next week)

**Comment by r9y9** [comment]
FYI: I added README https://github.com/r9y9/nnsvs/tree/optuna-test1/recipes/mixed/voc-multidb-latest

**Comment by r9y9** [comment]
I added another example recipe: https://github.com/r9y9/nnsvs/tree/optuna-test1/recipes/kiritan_singing/svs-world-resf0

To summarize, there are two recipes for building neural vocoders:
- [mixed/voc-multidb-latest](https://github.com/r9y9/nnsvs/tree/optuna-test1/recipes/mixed/voc-multidb-latest): a recipe for training a universal neural vocoder
- [kiritan_singing/svs-world-resf0](https://github.com/r9y9/nnsvs/tree/optuna-test1/recipes/kiritan_singing/svs-world-resf0): a recipe for buliding a complete SVS system with an optional neural vocoder

Although there's little documentation, I think now the implementation got in a good shape and people may want to try it on your own.

**Comment by r9y9** [comment]
I'll move the discussion to #72. Please check https://github.com/r9y9/nnsvs/issues/72#issuecomment-1096743842.

**Pull request closed without merging**
